.TH ITUNES-CLEAR-ORPHANED 1 "July 2025" "itunes-clear-orphaned 0.0.5"
.SH NAME
itunes-clear-orphaned \- remove orphaned files from an iTunes/Music library
.SH SYNOPSIS
.B itunes-clear-orphaned
.SH DESCRIPTION
.B itunes-clear-orphaned
is a utility for removing orphaned files from an iTunes library. It scans the specified
library file and media directory, identifies files that no longer exist on the file system,
and deletes them.
.SH AUTHOR
Written by the itunes-clear-orphaned contributors.
.SH COPYRIGHT
Copyright (C) 2025. Licensed under the MIT License.
