jobs:
  upload:
    permissions:
      contents: 'write'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6.0.2'
      - name: 'Stage release asset'
        run: 'cp dist/index.js itunes-clear-orphaned'
      - uses: 'softprops/action-gh-release@v3.0.0'
        with:
          draft: true
          files: 'itunes-clear-orphaned'
name: 'Upload dist'
'on':
  push:
    tags:
      - 'v*'
permissions:
  contents: 'write'
